# Generated by Django 3.0.5 on 2020-04-27 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200426_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='secondaryImages',
            field=models.ImageField(max_length=5, upload_to='images/'),
        ),
    ]
