# Generated by Django 3.0.5 on 2020-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_artimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerScienceP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('secondaryImages', models.ImageField(upload_to='images/')),
                ('ThirdImages', models.ImageField(upload_to='images/')),
                ('tools', models.TextField()),
                ('about', models.TextField()),
                ('learn', models.TextField()),
            ],
        ),
    ]
